### ISSUE TITLE
Tiny yolo v3 Training Error

### ISSUE THREAD

**Issue by tmsor7** [avBuffer/Yolov5_tf#8]
When I try to training this program using tiny yolo v3 (net_type=tiny), I got the under 
messages. 

train.py

Instructions for updating:
Use standard file APIs to check for files with this prefix.
  0%|          | 0/39782 [00:00<?, ?it/s]2020-08-26 16:00:13.648868: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [2,18,18,3,4] vs. [2,36,36,3,4]
	 [[{{node define_loss/bigger_box_loss/logistic_loss_2/mul}}]]
	 [[define_loss/prob_loss/add/_69]]
  (1) Invalid argument: Incompatible shapes: [2,18,18,3,4] vs. [2,36,36,3,4]
	 [[{{node define_loss/bigger_box_loss/logistic_loss_2/mul}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/sl/train.py", line 261, in <module>
    YoloTrain(net_type).train()
  File "/media/sl/train.py", line 201, in train
    self.trainable: True,})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [2,18,18,3,4] vs. [2,36,36,3,4]
	 [[node define_loss/bigger_box_loss/logistic_loss_2/mul (defined at media/sl/core/yolov3_tiny.py:197) ]]
	 [[define_loss/prob_loss/add/_69]]
  (1) Invalid argument: Incompatible shapes: [2,18,18,3,4] vs. [2,36,36,3,4]
	 [[node define_loss/bigger_box_loss/logistic_loss_2/mul (defined at media/sl/core/yolov3_tiny.py:197) ]]
0 successful operations.
0 derived errors ignored.

Plz check my problems

**Comment by tmsor7** [comment]
Problem is solved

**Comment by highhand31** [comment]
I've got the same error when using "tiny"!!

**Comment by avBuffer** [comment]
Hey all, Thanks, could you mind telling which net type selecting on backbone, such as darknet53 or mobilenet?
